/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import PMS.*;
import OMS.*;
import UMS.*;
import java.util.*;
import java.io.*;

/**
 *
 * @author jmyer
 */
public class BrowseItemsPanel extends javax.swing.JPanel {

    /**
     * Creates new form browseItemsPanel
     */
    public BrowseItemsPanel() {
        initComponents();
        
        String[] allCategories;
        
        this.categoryComboBox.removeAll();
        
        File abbreviationsFile = new File("listOfCategories.txt");
        
        String line;
        try {
            java.io.FileReader abbreviationsFileReader = new java.io.FileReader(abbreviationsFile);
            java.io.BufferedReader abbreviationsBufferedReader = new java.io.BufferedReader(abbreviationsFileReader);
            
            while((line = abbreviationsBufferedReader.readLine()) != null) {
                this.categoryComboBox.addItem(line);
            }
        } catch(Exception ex) {
            System.out.println("In BrowseItemsPanel() --" + ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseItemsLabel = new javax.swing.JLabel();
        searchByCategoryLabel = new javax.swing.JLabel();
        searchByIDLabel = new javax.swing.JLabel();
        IDSearchTextField = new javax.swing.JTextField();
        IDSearchLabel = new javax.swing.JLabel();
        searchByIDButton = new javax.swing.JButton();
        searchByCategoryButton = new javax.swing.JButton();
        categoryComboBox = new javax.swing.JComboBox<>();
        IDSearchLabel1 = new javax.swing.JLabel();

        browseItemsLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        browseItemsLabel.setText("Browse Items");

        searchByCategoryLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchByCategoryLabel.setText("Search By Category");

        searchByIDLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchByIDLabel.setText("Search By ID");

        IDSearchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        IDSearchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDSearchLabel.setText("ID");

        searchByIDButton.setText("Search");
        searchByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIDButtonActionPerformed(evt);
            }
        });

        searchByCategoryButton.setText("Search");
        searchByCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCategoryButtonActionPerformed(evt);
            }
        });

        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        IDSearchLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDSearchLabel1.setText("Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseItemsLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchByIDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IDSearchLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(IDSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(searchByIDLabel, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(searchByCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IDSearchLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(searchByCategoryLabel))))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(browseItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(searchByIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDSearchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(searchByCategoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDSearchLabel1))
                .addGap(18, 18, 18)
                .addComponent(searchByCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIDButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<ProductInfo> searchedProducts = new ArrayList<>();
        searchedProducts = PMS.ProductSearch.searchByID(WelcomeFrame.productList, this.IDSearchTextField.getText());
        SearchedProductsPanel.productsToDisplay = searchedProducts;
        
    }//GEN-LAST:event_searchByIDButtonActionPerformed

    private void searchByCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCategoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchByCategoryButtonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDSearchLabel;
    private javax.swing.JLabel IDSearchLabel1;
    private javax.swing.JTextField IDSearchTextField;
    private javax.swing.JLabel browseItemsLabel;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JButton searchByCategoryButton;
    private javax.swing.JLabel searchByCategoryLabel;
    private javax.swing.JButton searchByIDButton;
    private javax.swing.JLabel searchByIDLabel;
    // End of variables declaration//GEN-END:variables
}
