/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.*;
import GUI.*;
import static GUI.SearchedProductsPanel.productsToDisplay;
import OMS.*;
import PMS.*;
import UMS.*;

/**
 *
 * @author tyler
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.navigatorPanel1.setBrowseItemsPanelVisibility(true);
        this.navigatorPanel1.setShoppingCartPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
        this.navigatorPanel1.setSearchedProductsPanelVisibility(false);
        this.navigatorPanel1.setAccountPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigatorPanel1 = new GUI.NavigatorPanel();
        accountInformationButton = new javax.swing.JButton();
        browseItemsButton = new javax.swing.JButton();
        shoppingCartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountInformationButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        accountInformationButton.setText("Account Information");
        accountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInformationButtonActionPerformed(evt);
            }
        });

        browseItemsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        browseItemsButton.setText("Browse Items");
        browseItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseItemsButtonActionPerformed(evt);
            }
        });
        browseItemsButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                browseItemsButtonKeyPressed(evt);
            }
        });

        shoppingCartButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        shoppingCartButton.setText("Shopping Cart");
        shoppingCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigatorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(browseItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(shoppingCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accountInformationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseItemsButton)
                    .addComponent(shoppingCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountInformationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navigatorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shoppingCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingCartButtonActionPerformed
        // TODO add your handling code here:
        this.navigatorPanel1.setBrowseItemsPanelVisibility(false);
        this.navigatorPanel1.setShoppingCartPanelVisibility(true);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
        this.navigatorPanel1.setSearchedProductsPanelVisibility(false);
        this.navigatorPanel1.setAccountPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
        
        if(this.navigatorPanel1.searchedProductsPanel1.productsToOrder.size() > 0) {
            WelcomeFrame.currentOrder = new OrderInfo(WelcomeFrame.currentUser, this.navigatorPanel1.searchedProductsPanel1.productsToOrder, this.navigatorPanel1.searchedProductsPanel1.quantityList);
            this.navigatorPanel1.shoppingCartPanel1.updateFields(WelcomeFrame.currentOrder);
        }
    }//GEN-LAST:event_shoppingCartButtonActionPerformed

    private void browseItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseItemsButtonActionPerformed
        // TODO add your handling code here:
        this.navigatorPanel1.setBrowseItemsPanelVisibility(true);
        this.navigatorPanel1.setShoppingCartPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
        this.navigatorPanel1.setSearchedProductsPanelVisibility(false);
        this.navigatorPanel1.setAccountPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
    }//GEN-LAST:event_browseItemsButtonActionPerformed

    private void accountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInformationButtonActionPerformed
        // TODO add your handling code here:
        this.navigatorPanel1.accountPanel1.updateFields();
        this.navigatorPanel1.setBrowseItemsPanelVisibility(false);
        this.navigatorPanel1.setShoppingCartPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
        this.navigatorPanel1.setSearchedProductsPanelVisibility(false);
        this.navigatorPanel1.setAccountPanelVisibility(true);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
    }//GEN-LAST:event_accountInformationButtonActionPerformed

    private void browseItemsButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_browseItemsButtonKeyPressed
        // TODO add your handling code here:
        this.navigatorPanel1.setBrowseItemsPanelVisibility(false);
        this.navigatorPanel1.setShoppingCartPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
        this.navigatorPanel1.setSearchedProductsPanelVisibility(true);
        this.navigatorPanel1.setAccountPanelVisibility(false);
        this.navigatorPanel1.setOrderInfoCollectionPanelVisibility(false);
    }//GEN-LAST:event_browseItemsButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountInformationButton;
    private javax.swing.JButton browseItemsButton;
    private GUI.NavigatorPanel navigatorPanel1;
    private javax.swing.JButton shoppingCartButton;
    // End of variables declaration//GEN-END:variables
}
