/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.*;
import GUI.*;
import OMS.*;
import PMS.*;
import UMS.*;

/**
 *
 * @author jmyer
 */
public class NavigatorPanel extends javax.swing.JPanel {
    
    public void setOrderInfoCollectionPanelVisibility(boolean input) {
        this.orderInfoCollectionPanel1.setVisible(input);
    }
    public void setBrowseItemsPanelVisibility(boolean input) {
        this.browseItemsPanel1.setVisible(input);
    }
    public void setSearchedProductsPanelVisibility(boolean input) {
        this.searchedProductsPanel1.setVisible(input);
    }
    public void setShoppingCartPanelVisibility(boolean input) {
        this.shoppingCartPanel1.setVisible(input);
    }
    public void setAccountPanelVisibility(boolean input) {
        this.accountPanel1.setVisible(input);
    }

    /**
     * Creates new form NavigatorPanel
     */
    public NavigatorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseItemsPanel1 = new GUI.BrowseItemsPanel();
        shoppingCartPanel1 = new GUI.ShoppingCartPanel();
        searchedProductsPanel1 = new GUI.SearchedProductsPanel();
        orderInfoCollectionPanel1 = new GUI.OrderInfoCollectionPanel();
        accountPanel1 = new GUI.AccountPanel();

        setLayout(new java.awt.CardLayout());
        add(browseItemsPanel1, "card2");
        add(shoppingCartPanel1, "card3");
        add(searchedProductsPanel1, "card4");
        add(orderInfoCollectionPanel1, "card5");
        add(accountPanel1, "card6");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public GUI.AccountPanel accountPanel1;
    public GUI.BrowseItemsPanel browseItemsPanel1;
    public GUI.OrderInfoCollectionPanel orderInfoCollectionPanel1;
    public GUI.SearchedProductsPanel searchedProductsPanel1;
    public GUI.ShoppingCartPanel shoppingCartPanel1;
    // End of variables declaration//GEN-END:variables
}
