/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import PMS.*;
import OMS.*;
import UMS.*;
import java.util.*;

/**
 *
 * @author jmyer
 */
public class SearchedProductsPanel extends javax.swing.JPanel {
    public static ArrayList<ProductInfo> productsToDisplay;
    public static ArrayList<ProductInfo> productsToOrder = new ArrayList<>();
    public static int[] quantityList = new int[0];
    private int timesButtonOnePressed = 0;
    
    public void updateDisplayedItems() {
        for(int index = 0; index < productsToDisplay.size(); index++) {
            if(index < 1) {
                this.productOne.setAllFields(productsToDisplay.get(0));
            } else if(index < 2) {
                this.productTwo.setAllFields(productsToDisplay.get(1));
            } else if(index < 3) {
                this.productThree.setAllFields(productsToDisplay.get(2));
            } else if(index < 4) {
                this.productFour.setAllFields(productsToDisplay.get(3));
            } else if(index < 5) {
                this.productFive.setAllFields(productsToDisplay.get(4));
            } else if(index < 6) {
                this.productSix.setAllFields(productsToDisplay.get(5));
            }
        }
    }

    /**
     * Creates new form SearchedProductsPanel
     */
    public SearchedProductsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productTwo = new GUI.ProductInfoPanel();
        productThree = new GUI.ProductInfoPanel();
        productFour = new GUI.ProductInfoPanel();
        productFive = new GUI.ProductInfoPanel();
        productSix = new GUI.ProductInfoPanel();
        productOne = new GUI.ProductInfoPanel();
        addButtonTwo = new javax.swing.JButton();
        addButtonOne = new javax.swing.JButton();
        addButtonThree = new javax.swing.JButton();
        addButtonFour = new javax.swing.JButton();
        addButtonFive = new javax.swing.JButton();
        addButtonSix = new javax.swing.JButton();
        nextPageButton = new javax.swing.JButton();
        previousPageButton = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        manufacturerLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        availabilityLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();

        addButtonTwo.setText("Add To Cart");

        addButtonOne.setText("Add To Cart");
        addButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonOneActionPerformed(evt);
            }
        });

        addButtonThree.setText("Add To Cart");

        addButtonFour.setText("Add To Cart");

        addButtonFive.setText("Add To Cart");

        addButtonSix.setText("Add To Cart");

        nextPageButton.setText("Next Page");

        previousPageButton.setText("Previous Page");

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDLabel.setText("Product ID");

        manufacturerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manufacturerLabel.setText("Manufacturer");

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityLabel.setText("Quantity");

        availabilityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        availabilityLabel.setText("Availability");

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceLabel.setText("Price");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(previousPageButton)
                        .addGap(331, 331, 331)
                        .addComponent(refreshButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButtonSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButtonFive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButtonTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButtonThree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButtonFour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nextPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(IDLabel)
                .addGap(88, 88, 88)
                .addComponent(manufacturerLabel)
                .addGap(94, 94, 94)
                .addComponent(quantityLabel)
                .addGap(101, 101, 101)
                .addComponent(availabilityLabel)
                .addGap(116, 116, 116)
                .addComponent(priceLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(manufacturerLabel)
                    .addComponent(quantityLabel)
                    .addComponent(availabilityLabel)
                    .addComponent(priceLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(addButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(addButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonOneActionPerformed
        // TODO add your handling code here:
        if(this.timesButtonOnePressed == 0) {
           productsToOrder.add(productsToDisplay.get(0)); 
           quantityList = OrderInfo.appendIntList(quantityList, 1);
        }
        quantityList[0]++;
        this.timesButtonOnePressed++;
    }//GEN-LAST:event_addButtonOneActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        this.updateDisplayedItems();
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton addButtonFive;
    private javax.swing.JButton addButtonFour;
    private javax.swing.JButton addButtonOne;
    private javax.swing.JButton addButtonSix;
    private javax.swing.JButton addButtonThree;
    private javax.swing.JButton addButtonTwo;
    private javax.swing.JLabel availabilityLabel;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JButton nextPageButton;
    private javax.swing.JButton previousPageButton;
    private javax.swing.JLabel priceLabel;
    private GUI.ProductInfoPanel productFive;
    private GUI.ProductInfoPanel productFour;
    private GUI.ProductInfoPanel productOne;
    private GUI.ProductInfoPanel productSix;
    private GUI.ProductInfoPanel productThree;
    private GUI.ProductInfoPanel productTwo;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
